name: Publish

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: Deps
      run: |
        sudo apt-get update
        sudo apt install -y libudev-dev

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
