name: Rust Lint and Test

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Rust Toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            override: true

        - name: Toolchain in nightly mode
          run: |
            rustup component add rustfmt --toolchain nightly
            rustup component add clippy --toolchain nightly
    
        - name: Check
          run: |
            cargo check --all --tests
        
        - name: Build
          run: |
            cargo build
        
        - name: Test
          run: |
            cargo test
        
        - name: Format
          run: |
            cargo fmt --all -- --check
                
        - name: Lint
          run: |
            cargo clippy --all-targets --all-features -- -D warnings
